<?php

/**
 * AgreementModelTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgreementModelTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgreementModelTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AgreementModelType');
    }
}