<?php

/**
 * AgreementModelValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgreementModelValueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgreementModelValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AgreementModelValue');
    }

    /**
     * Get period value from model
     * @param $model
     */
    public static function getPeriodValueFromModel($model) {
        $values = $model['Values'];

        foreach ($values as $key => $value_data) {
            $field = AgreementModelFieldTable::getInstance()->find($value_data['field_id']);
            if ($field && $field->isPeriodField()) {
                $value = $value_data['value'];
                if (empty($value)) {
                    return false;
                } else {
                    $value = explode('-', $value);
                    if (!empty($value[1])) {
                        $value = $value[1];

                        $value = explode('.', $value);
                        $dt = DateTime::createFromFormat('y', $value[2]);

                        $value = sprintf('%s-%s-%s', $value[0], $value[1], $dt->format('Y'));
                    } else
                        return false;
                }

                return $value;
            }
        }

        return false;
    }
}