<?php

/**
 * DealerWorkStatisticTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DealerWorkStatisticTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DealerWorkStatisticTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DealerWorkStatistic');
    }
}