<?php

/**
 * Dealer
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Dealer extends BaseDealer
{

    const TYPE_PKW = 1;
    const TYPE_NFZ = 2;
    const TYPE_NFZ_PKW = 3;

    function getShortNumber()
    {
        $number_length = $this->getNumberLength();
        if (is_null($number_length)) {
            $number_length = 3;
        }

        return substr($this->getNumber(), -$number_length);
    }

    function __toString()
    {
        return '<span style="display: inline-block; width: 36px;">' . $this->getShortNumber() . '</span> ' . $this->getName();
    }

    public function getSimpleName()
    {
        return $this->getName();
    }

    public function isPKW() {
        return $this->getDealerType() == self::TYPE_PKW;
    }

    public function isNFZ() {
        return $this->getDealerType() == self::TYPE_NFZ;
    }

    public function isNFZ_PKW() {
        return $this->getDealerType() == self::TYPE_NFZ_PKW;
    }

    public function getDealerTypeLabel() {
        if ($this->isPKW()) {
            return 'PKW';
        } else if ($this->isNFZ()) {
            return 'NFZ ';
        } else {
            return 'PKW+NFZ';
        }
    }

    public function getNameAndNumber() {
        return sprintf('[%s] - %s', $this->getShortNumber(), $this->getName());
    }
}
