<?php

/**
 * DiscussionLastRead
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DiscussionLastRead extends BaseDiscussionLastRead
{
    public function findMessage($id) {
        return DiscussionLastReadTable::getInstance()->createQuery()->where('message_id = ?', $id)->count() > 0 ? true : false;
    }
}