<?php
/**
 * Created by PhpStorm.
 * User: kostet
 * Date: 20.03.2018
 * Time: 13:02
 */

class ActivityBudgetPointsExtendedStatisticStatuses extends ActivityStatusWithExtendedStatistic {
    public function getStatus ()
    {
        parent::getStatus(); // TODO: Change the autogenerated stub

        if ($this->activity_models_created_count > 0) {
            $activityStatisticStatus = $this->activity->isActivityStatisticComplete($this->user, null, true, $this->year, $this->quarter, $this->consider_activity_quarter ? array( 'check_by_quarter' => true ) : null);

            $activityModelsComplete = Utils::checkModelsCompleted($this->activity, $this->dealer, $this->year, $this->quarter); /*AgreementModelTable::getInstance()
            ->createQuery('am')
            ->select('id')
            ->leftJoin('am.Report r')
            ->where('am.activity_id = ? and am.dealer_id = ?', array($this->activity->getId(), $this->dealer->getId()))
            //->andWhere('year(r.updated_at) = ? and quarter(r.updated_at) = ?', array($this->year, $this->quarter))
            ->andWhere('am.status = ? and r.status = ?', array('accepted', 'accepted'))
            ->andWhere('model_type_id != ?', Activity::CONCEPT_MODEL_TYPE_ID)
            ->orderBy('am.id ASC')
            ->execute(array(), Doctrine_Core::HYDRATE_ARRAY);*/

            if ($activityModelsComplete && $activityStatisticStatus) {
                return array( 'status' => ActivitiesBudgetByControlPoints::ACTIVITY_TOTAL_COMPLETED, 'msg' => 'Активность выполнена, статистика заполнена' );
            }

            //Если в активности есть выолненныйе заявки
            if ($activityModelsComplete) {

                if (!$activityStatisticStatus) {
                    return array( 'status' => ActivitiesBudgetByControlPoints::ACTIVITY_COMPLETED_WITHOUT_STATISTIC, 'msg' => 'Активность выполнена, но статистика не заполнена' );
                }

                return array( 'status' => ActivitiesBudgetByControlPoints::ACTIVITY_TOTAL_COMPLETED, 'msg' => 'Активность выполнена' );
            }

            //В активности есть созданные заявки
            return array( 'status' => ActivitiesBudgetByControlPoints::ACTIVITY_IN_WORK, 'msg' => 'К активности приступили' );
        }

        //Если в активности ничего не создано
        return array( 'status' => ActivitiesBudgetByControlPoints::ACTIVITY_NOT_START, 'msg' => 'Активность не начата' );
    }
}
