all:
  stylesheets: [manager, user_management]
  javascripts:
   - utils/utils.js

modelSuccess:
  has_layout: false
modelError:
  has_layout: false
reportSuccess:
  has_layout: false
reportError:
  has_layout: false
  